### ISSUE TITLE
submodule not update

### ISSUE THREAD

**Issue by heyfluke** [appunite/AndroidFFmpeg#74]
Unable to checkout '999b753ff0f4dc872077f4fa90d465e948cbe656' in submodule path 'FFmpegLibrary/jni/x264'

I think someone may forget to push his 999b753ff0f4dc872077f4fa90d465e948cbe656 commit in x264.

**Comment by vishot** [comment]
me too.

**Comment by ejdelros08** [comment]
I'm sorry but I don't know why this issue is even closed. I'ts 2015 now and this same issue is occurring:

fatal: reference is not a tree: 999b753ff0f4dc872077f4fa90d465e948cbe656
Unable to checkout '999b753ff0f4dc872077f4fa90d465e948cbe656' in submodule path 'FFmpegLibrary/jni/x264'

How do we get to clone all the necessary files successfully? Thank you!

**Comment by matthewn4444** [comment]
In my fork, I updated the location and build script [here](https://github.com/matthewn4444/VPlayer_lib/commit/187aff339592d520ab4791ce67e558472fb2a62c). Down the page at **ffmpeg_build/x264** shows the subproject hash I changed, you can use this one to build with x264.

The other option is try to use someone else's fork (under the network tab).
